### ISSUE TITLE
Total hours worked don't accept 0 when updating volunteering event

### ISSUE THREAD

**Issue by mrkvon** [lamanchy/bis#11]
When `PATCH`ing `/api/frontend/events/:eventId/` with body `{ "record": { "total_hours_worked": 0 } }` for a volunteering event, we get response `400` with body

```json
["Odpracováno člověkohodin nevyplněno"]
```

is that a feature or a bug? I'd think that 0 hours worked are acceptable, but maybe not for a volunteering event?

In any case, the error message is wrong in this case. (it's filled, just falsy)

**Comment by lamanchy** [comment]
```
        if self.event.is_volunteering() and not self.total_hours_worked:
            raise ValidationError('Odpracováno člověkohodin nevyplněno')
```
It is a feature ;)

Do you use the error message? I can make another one for zero, np.

**Comment by mrkvon** [comment]
No need to change, for now. We won't need the backend error message if we change FE error validation. I'm trying to figure out whether we should.

So far i only know that the field is required (and non-negative obviously). In any case it's not a big thing, not worth a big discussion, and i'm fine either way (depending on what project owners want), or leaving things as they are, for now... After all, we're still not protecting even against negative values in FE! 😄 

So I'll close this, and if there is a need to dig into this further, someone can reopen...

---

The philosophical issue is the following:

In principle, is `required` rule for number distinct from `non-zero`? I think it is. E.g. `undefined` would _not_ satisfy such `required` rule, but `0` would. A random validation library ([yup](https://www.npmjs.com/package/yup)) also thinks so.

I understand that Python treats 0 as falsy, and therefore `0` is rejected by the `required` rule you quote above.

So the way the rule works here is different from how it is in my head...
