### ISSUE TITLE
POST /api/frontend/get_unknown_user/ returns inconsistent qualifications

### ISSUE THREAD

**Issue by mrkvon** [lamanchy/bis#12]
When fetching a user via `GET /api/frontend/users/:id/`, we receive `user.qualifications` in the following format:

```ts
{
  category: QualificationCategory, // object with id, slug, ...
  valid_since: string, // date
  valid_till: string, // date
  approved_by: QualificationApprovedBy //object
}[]
```
However, when fetching a user via `POST
/api/frontend/get_unknown_user/`, the format of `user.qualifications` is different:

```ts
{
  category: number // <= this is inconsistent
  valid_since: string,
  valid_till: string,
  approved_by: QualificationApprovedBy
}[]
```

In particular, `user.qualifications[].category` is just category id

This is inconsistent and causes unexpected bugs when using data from both endpoints interchangeably. Is it possible to fix?

**Comment by lamanchy** [comment]
@mrkvon behaviour of serializes changes based on method, serializers with id are expanded only when the method is get, so I changed the endpoint to GET instead of POST. ;)

**Comment by mrkvon** [comment]
@lamanchy That works for us, thank you!
We fixed frontend accordingly in https://github.com/mrkvon/bis-frontend/pull/139
