### ISSUE TITLE
User as main_organizer passes only if their qualifications match exactly

### ISSUE THREAD

**Issue by mrkvon** [lamanchy/bis#13]
When user has one of parent qualifications, she doesn't get recognized as valid main_organizer.

This can be reproduced e.g. when saving event `other` - `public__other__for_public` - `for_kids` (at least `kid_intern` necessary) with main organizer `Test2 Test` (`consultant_for_kids`).

I believe this is related to https://github.com/lamanchy/bis/blob/e39bf6cff1678aa89463ff6b7b04ddd7143d7900/backend/bis/models.py#L521-L527 and https://github.com/lamanchy/bis/blob/c80980fea0c7c2f63f1f1f30427a5351d332a8ce/backend/categories/models.py#L48-L51

because we need user's qualification or any child qualifications to match `required_one_of`, not parent qualifications.

Alternatively, we need required_one_of or any of their parents to match user's qualifications (exactly).

Currently, we check the qualifications' ordered graph in wrong direction...

**Comment by lamanchy** [comment]
@mrkvon You are completely right, it's fixed ;)
