### ISSUE TITLE
GET /api/web/events/:id/ doesn't return event.registration.alternative_registration_link

### ISSUE THREAD

**Issue by mrkvon** [lamanchy/bis#15]
The title says it all. I think it should return that information. We need it to display the correct application form for public.

**Comment by lamanchy** [comment]
![image](https://user-images.githubusercontent.com/4850265/212470982-2086d613-049a-4e9e-93da-275657a76f11.png)

Wel... :D

**Comment by lamanchy** [comment]
Or am I missing something?

**Comment by mrkvon** [comment]
The generated documentation doesn't always reflect reality, especially when it comes to irregular variations of data types.

This is a response to `GET /api/frontend/events/:id/`:

```json
{
    "id": 10570,
    ...
    "registration": {
        "is_registration_required": true,
        "alternative_registration_link": "https://example.com/prihlaska",
        "is_event_full": false,
        "questionnaire": null
    },
    ...
}
```

and this is a response to `GET /api/web/events/:id/`:

```json
{
    "id": 10570,
    ...
    "registration": {
        "is_registration_required": true,
        "is_event_full": false,
        "questionnaire": null
    }
}
```

_edited to highlight only the relevant data difference_

**Comment by lamanchy** [comment]
@mrkvon oh, I'm sorry, I missed the "web" part. Added.
