### ISSUE TITLE
API: Fetching user by id fails with 500

### ISSUE THREAD

**Issue by mrkvon** [lamanchy/bis#3]
`GET /api/frontend/users/:id/`

Response status: `500`

Response body:

```html
<!doctype html>
<html lang="en">

<head>
	<title>Server Error (500)</title>
</head>

<body>
	<h1>Server Error (500)</h1>
	<p></p>
</body>

</html>
```

Only tested with production. Haven't tested locally.

The same with GET `/api/frontend/users/?page=1`

**Comment by lamanchy** [comment]
Yess, sorry, I forgot to push the fix, it's there now.

**Comment by mrkvon** [comment]
Thanks a lot! It is. :)
