### ISSUE TITLE
Search organizers

### ISSUE THREAD

**Issue by lamanchy** [lamanchy/bis#7]
@mrkvon:
Ahoj, máme endpoint(y) na hledání potenciálních organizátorů/organizátorek (nevím, jak je ta množina definovaná) do organizátorského týmu? něco jako GET /api/frontend/users/?search=castjmenaneboprezdivkynebomoznaemail  ? (nejspíš by měl vracet jen omezená data o uživatelce/uživateli. například asi ne datum narození, aby organizátor neměl možnost všechny editovat... v podstatě stačí jen Jméno, Příjmení, Přezdívka, Základní článek, možná místo bydliště (stačí město/ves))

**Comment by lamanchy** [comment]
Odpovím s dovolením česky, bude to delší:

V zásadě jsou v BISu uživatelé které máš právo vidět (všichni jsou na api/frontend/users/) to jsou spoluorgové / účastníci / členvé tvého článku (i když to se netýká frontendu, ale pro představu) a pak jsou všichni ti, co je vidět nemáš.

Jako sprostý přihlášený uživatel (neorg) je jen vidíš a nevidíš u nich údaje jako členství, a můžeš editovat jen sebe (naopak u sebe vidíš i dary atp).

Pokud jsi org, tak platí že všechny uživatele, co vidíš, tak je můžeš i editovat. (ze zadání, lze polemizovat, jeslti je to dobrý nápad).

A pokud chceš přidat uživatele co nevidíš jako orga/účastníka, pak musíš prokázat, že ho znáš tím, že zadáš jeho datum narození. (opět, takto to funguje v aktuálním BISu)

Mnou navržené flow pro přidání účastníka / organizátora (je to jedno) je takovéto:
Nejdříve uvidíš filtr mezi lidmi, které vidíš, "fulltext" search bude na api/fronted/users/?search=emailcijmenowhatever
Pokud uživatele najdeš, znamená to, že už ho vidíš a můžeš použít jeho id kam potřebuješ.
Pokud ho nenajdeš, bude tam tlačítko "přidat uživatele"
Začneš s formulářem, kam zadáš jen jméno + příjmení + datum narození (tato kombinace je v DB vždy unikátní a identifikuje uživatele alternativně jako email, protože dítě nemá email)
Pokud BIS daného uživatele nenajde, otevře se ti formulář, kam doplníš zbytek informací o uživateli a vytvoří se nový.
Pokud ho to najde, pak... ti to vrátí jeho id, které můžeš použít pro přidání mezi orgy/účastníky a tím pádem ho příště už uvidíš mezi api/frontend/users/
A ano, bylo by tam omezení, abys pro kombinaci jméno a příjmení nemohl po sobě poslat 365 requestů a zjistit tak všechny ostatní údaje, které chceš.

Hm?

**Comment by mrkvon** [comment]
Díky, `api/fronted/users/?search=emailcijmenowhatever` vyřeší naše potřeby pro hledání potenciálních organizátorů. Přidávání organizátora mimo _můj okruh_ zatím neřeším. Flow přidávání uživatele nejspíš bude tak nějak vypadat, ale detaily jsem ještě nestudoval:
https://www.canva.com/design/DAFMNwnyh-I/8Kb3u63ndrFce8XJ94by2A/edit?utm_content=DAFMNwnyh-I&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton#27

Víc bude vědět @agatatalita @talitadzikzlasu

**Comment by lamanchy** [comment]
Jop, to vypadá fajně, a tedy v zásadě velmi podobné flow to bude chtít i při přidávání organizátorů. Udělám tedy i ten endpoint pro jméno+příjmení+datum narození ;⁠-⁠)

**Comment by lamanchy** [comment]
Pole k vyhledávání: `search_fields = 'all_emails__email', 'phone', 'first_name', 'last_name', 'nickname'`

Get unknown user: `/api/frontend/get_unknown_user/`
