### ISSUE TITLE
How to save optional accommodation to event?

### ISSUE THREAD

**Issue by mrkvon** [lamanchy/bis#8]
According to https://docs.google.com/document/d/1p3nz0-kVJxwN_pRCYYyhy0BObyGox6LDk35RQPADT4g/edit?disco=AAAAc3SBnZc:

> Ubytování (*)!
> [...]
> "Vikendovka" + " tábory" = povinna polozka
>
> "Jednorazova nebo akce bez adresare = nepovinná"

So, can we save empty string to accommodation, or omit it? I haven't found a way to do it.

Tried with https://dev.bis.lomic.cz/api/#/frontend/frontend_events_partial_update and

- body `{ "group": 3, "propagation": { "accommodation": "", [...] } }` ➡️  (`{ "propagation": { "accommodation": ["Toto pole nesmí být prázdné."] } }`)
- body `{ "group": 3, "propagation": { [...] } }` without `propagation.accommodation` ➡️  (`{ "propagation": { "accommodation": ["Toto pole je vyžadováno."] } }`)

Until now, i've worked around this issue by saving `"."` to that field by default

If unsure, we could also confirm with project owners that the requirement in the linked document is correct.

**Comment by lamanchy** [comment]
My bad, will fix ;)

**Comment by lamanchy** [comment]
Fixed
